# Generated by Django 5.0.4 on 2024-04-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_user_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default='7W1MSiMRpqnO27wnIjJ2', max_length=20),
        ),
    ]
