# Generated by Django 5.0.4 on 2024-04-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_user_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(default='rvQaSxelAa9aczKZpCdi', max_length=20),
        ),
    ]
